import type { Dish, Category } from "@/contexts/AppContext"

export const mockDishes: Dish[] = [
  // 推荐菜品
  {
    name: "宫保鸡丁",
    rating: 4.5,
    price: "¥28",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "经典川菜，鸡肉嫩滑，花生香脆",
    description: "选用优质鸡胸肉，配以花生米和干辣椒，麻辣鲜香，是川菜中的经典代表",
    category: "推荐",
  },
  {
    name: "麻婆豆腐",
    rating: 4.2,
    price: "¥18",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "嫩滑豆腐配麻辣酱汁，下饭神器",
    description: "传统川菜，豆腐嫩滑，麻辣适中，老少皆宜的经典家常菜",
    category: "推荐",
  },
  {
    name: "糖醋里脊",
    rating: 4.7,
    price: "¥32",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "酸甜可口，外酥内嫩，家庭最爱",
    description: "优质里脊肉，酸甜适中，外酥内嫩，老少皆宜的经典菜品",
    category: "推荐",
  },

  // 热菜
  {
    name: "红烧肉",
    rating: 4.6,
    price: "¥35",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "肥瘦相间，入口即化，传统江南风味",
    description: "选用优质五花肉，慢火炖煮，色泽红亮，肥而不腻",
    category: "热菜",
  },
  {
    name: "清蒸鲈鱼",
    rating: 4.4,
    price: "¥48",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "鲜嫩鱼肉，清淡健康，保持原汁原味",
    description: "新鲜鲈鱼，清蒸工艺，营养价值高，口感鲜美",
    category: "热菜",
  },
  {
    name: "水煮鱼",
    rating: 4.3,
    price: "¥42",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "麻辣鲜香，鱼肉嫩滑，汤汁浓郁",
    description: "新鲜草鱼配豆芽菜，麻辣鲜香，是川菜中的人气菜品",
    category: "热菜",
  },
  {
    name: "回锅肉",
    rating: 4.5,
    price: "¥26",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "川菜之王，肥瘦相间，下饭首选",
    description: "传统川菜，选用五花肉和青椒，味道浓郁，是川菜的代表作",
    category: "热菜",
  },

  // 素食
  {
    name: "蒜蓉西兰花",
    rating: 4.1,
    price: "¥16",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "清爽蔬菜，营养丰富，蒜香浓郁",
    description: "新鲜西兰花，爆炒至脆嫩，保持营养价值",
    category: "素食",
  },
  {
    name: "酸辣土豆丝",
    rating: 4.0,
    price: "¥12",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "经典家常菜，酸辣开胃，爽脆可口",
    description: "土豆丝切得细如发丝，酸辣适中，是经典的家常菜",
    category: "素食",
  },
  {
    name: "干煸四季豆",
    rating: 4.2,
    price: "¥18",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "川菜经典，四季豆香脆，配菜丰富",
    description: "四季豆干煸至微焦，配以肉末和榨菜，香味浓郁",
    category: "素食",
  },
  {
    name: "地三鲜",
    rating: 4.3,
    price: "¥22",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "东北名菜，茄子土豆青椒，味道浓郁",
    description: "茄子、土豆、青椒三种蔬菜的完美组合，营养丰富",
    category: "素食",
  },

  // 开胃菜
  {
    name: "小笼包",
    rating: 4.8,
    price: "¥24",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "皮薄馅大，汤汁丰富，上海经典小吃",
    description: "现包现蒸，一口一个，汤汁鲜美，是上海的招牌小吃",
    category: "开胃菜",
  },
  {
    name: "锅贴",
    rating: 4.5,
    price: "¥20",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "底部金黄酥脆，馅料鲜美多汁",
    description: "猪肉韭菜馅，煎制工艺，外酥内嫩，是经典的煎饺",
    category: "开胃菜",
  },
  {
    name: "蒸蛋羹",
    rating: 4.3,
    price: "¥12",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "嫩滑如丝，营养丰富，老少皆宜",
    description: "鸡蛋蒸至嫩滑，口感如丝，撒上葱花，营养美味",
    category: "开胃菜",
  },
  {
    name: "凉拌黄瓜",
    rating: 4.1,
    price: "¥10",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "清爽解腻，爽脆可口，完美开胃菜",
    description: "新鲜黄瓜配蒜泥醋汁，清爽解腻，是很好的开胃菜",
    category: "开胃菜",
  },
  {
    name: "口水鸡",
    rating: 4.6,
    price: "¥28",
    photoUrl: "/placeholder.svg?height=300&width=300",
    summary: "麻辣鲜香，鸡肉嫩滑，川菜经典",
    description: "白切鸡配特制麻辣调料，口感丰富，是川菜中的经典凉菜",
    category: "开胃菜",
  },
]

export const mockCategories: Category[] = [
  { id: "推荐", name: "推荐", count: 3 },
  { id: "热菜", name: "热菜", count: 4 },
  { id: "素食", name: "素食", count: 4 },
  { id: "开胃菜", name: "开胃菜", count: 5 },
] 